"""
build_static_tickers.py
Generates config/tickers.json with ~500 carefully curated US stocks + ETFs.
Run: python build_static_tickers.py
"""
import json, os

_DIR = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(_DIR, "config", "tickers.json")

TICKERS = [
    # ─── MEGA CAP TECH ───────────────────────────────────────────────────────────
    {"t":"AAPL","n":"Apple Inc.","s":"Technology"},
    {"t":"MSFT","n":"Microsoft Corporation","s":"Technology"},
    {"t":"NVDA","n":"NVIDIA Corporation","s":"Technology"},
    {"t":"GOOGL","n":"Alphabet Inc. Class A","s":"Technology"},
    {"t":"GOOG","n":"Alphabet Inc. Class C","s":"Technology"},
    {"t":"AMZN","n":"Amazon.com Inc.","s":"Consumer Discretionary"},
    {"t":"META","n":"Meta Platforms Inc.","s":"Technology"},
    {"t":"TSLA","n":"Tesla Inc.","s":"Consumer Discretionary"},
    {"t":"AVGO","n":"Broadcom Inc.","s":"Technology"},
    {"t":"ORCL","n":"Oracle Corporation","s":"Technology"},
    # ─── SOFTWARE ────────────────────────────────────────────────────────────────
    {"t":"CRM","n":"Salesforce Inc.","s":"Technology"},
    {"t":"ADBE","n":"Adobe Inc.","s":"Technology"},
    {"t":"NOW","n":"ServiceNow Inc.","s":"Technology"},
    {"t":"INTU","n":"Intuit Inc.","s":"Technology"},
    {"t":"SNOW","n":"Snowflake Inc.","s":"Technology"},
    {"t":"PLTR","n":"Palantir Technologies","s":"Technology"},
    {"t":"DDOG","n":"Datadog Inc.","s":"Technology"},
    {"t":"PANW","n":"Palo Alto Networks","s":"Technology"},
    {"t":"CRWD","n":"CrowdStrike Holdings","s":"Technology"},
    {"t":"NET","n":"Cloudflare Inc.","s":"Technology"},
    {"t":"ZS","n":"Zscaler Inc.","s":"Technology"},
    {"t":"OKTA","n":"Okta Inc.","s":"Technology"},
    {"t":"WDAY","n":"Workday Inc.","s":"Technology"},
    {"t":"MDB","n":"MongoDB Inc.","s":"Technology"},
    {"t":"GTLB","n":"GitLab Inc.","s":"Technology"},
    {"t":"HUBS","n":"HubSpot Inc.","s":"Technology"},
    {"t":"VEEV","n":"Veeva Systems","s":"Technology"},
    {"t":"TTD","n":"Trade Desk Inc.","s":"Technology"},
    {"t":"ANET","n":"Arista Networks","s":"Technology"},
    {"t":"SHOP","n":"Shopify Inc.","s":"Technology"},
    {"t":"ZM","n":"Zoom Video Communications","s":"Technology"},
    {"t":"DOCU","n":"DocuSign Inc.","s":"Technology"},
    {"t":"TWLO","n":"Twilio Inc.","s":"Technology"},
    {"t":"ASAN","n":"Asana Inc.","s":"Technology"},
    {"t":"AI","n":"C3.ai Inc.","s":"Technology"},
    {"t":"PATH","n":"UiPath Inc.","s":"Technology"},
    {"t":"SOUN","n":"SoundHound AI","s":"Technology"},
    {"t":"BBAI","n":"BigBear.ai Holdings","s":"Technology"},
    {"t":"SMCI","n":"Super Micro Computer","s":"Technology"},
    # ─── SEMICONDUCTORS ──────────────────────────────────────────────────────────
    {"t":"AMD","n":"Advanced Micro Devices","s":"Technology"},
    {"t":"INTC","n":"Intel Corporation","s":"Technology"},
    {"t":"QCOM","n":"Qualcomm Inc.","s":"Technology"},
    {"t":"TXN","n":"Texas Instruments","s":"Technology"},
    {"t":"AMAT","n":"Applied Materials","s":"Technology"},
    {"t":"LRCX","n":"Lam Research","s":"Technology"},
    {"t":"KLAC","n":"KLA Corporation","s":"Technology"},
    {"t":"MRVL","n":"Marvell Technology","s":"Technology"},
    {"t":"ASML","n":"ASML Holding NV","s":"Technology"},
    {"t":"MU","n":"Micron Technology","s":"Technology"},
    {"t":"MPWR","n":"Monolithic Power Systems","s":"Technology"},
    {"t":"ON","n":"ON Semiconductor","s":"Technology"},
    {"t":"SWKS","n":"Skyworks Solutions","s":"Technology"},
    {"t":"QRVO","n":"Qorvo Inc.","s":"Technology"},
    {"t":"WOLF","n":"Wolfspeed Inc.","s":"Technology"},
    {"t":"SOXL","n":"Direxion Daily Semi Bull 3X ETF","s":"ETF"},
    {"t":"SOXS","n":"Direxion Daily Semi Bear 3X ETF","s":"ETF"},
    # ─── HARDWARE / IT ───────────────────────────────────────────────────────────
    {"t":"CSCO","n":"Cisco Systems","s":"Technology"},
    {"t":"IBM","n":"IBM Corporation","s":"Technology"},
    {"t":"HPQ","n":"HP Inc.","s":"Technology"},
    {"t":"HPE","n":"Hewlett Packard Enterprise","s":"Technology"},
    {"t":"DELL","n":"Dell Technologies","s":"Technology"},
    {"t":"WDC","n":"Western Digital","s":"Technology"},
    {"t":"STX","n":"Seagate Technology","s":"Technology"},
    {"t":"NTAP","n":"NetApp Inc.","s":"Technology"},
    {"t":"PSTG","n":"Pure Storage","s":"Technology"},
    {"t":"JNPR","n":"Juniper Networks","s":"Technology"},
    {"t":"FFIV","n":"F5 Inc.","s":"Technology"},
    # ─── FINANCE ─────────────────────────────────────────────────────────────────
    {"t":"JPM","n":"JPMorgan Chase & Co.","s":"Finance"},
    {"t":"BAC","n":"Bank of America","s":"Finance"},
    {"t":"WFC","n":"Wells Fargo","s":"Finance"},
    {"t":"GS","n":"Goldman Sachs","s":"Finance"},
    {"t":"MS","n":"Morgan Stanley","s":"Finance"},
    {"t":"C","n":"Citigroup Inc.","s":"Finance"},
    {"t":"USB","n":"U.S. Bancorp","s":"Finance"},
    {"t":"PNC","n":"PNC Financial Services","s":"Finance"},
    {"t":"BK","n":"Bank of New York Mellon","s":"Finance"},
    {"t":"STT","n":"State Street Corp.","s":"Finance"},
    {"t":"AXP","n":"American Express","s":"Finance"},
    {"t":"COF","n":"Capital One Financial","s":"Finance"},
    {"t":"DFS","n":"Discover Financial Services","s":"Finance"},
    {"t":"SYF","n":"Synchrony Financial","s":"Finance"},
    {"t":"V","n":"Visa Inc.","s":"Finance"},
    {"t":"MA","n":"Mastercard Inc.","s":"Finance"},
    {"t":"PYPL","n":"PayPal Holdings","s":"Finance"},
    {"t":"SQ","n":"Block Inc.","s":"Finance"},
    {"t":"COIN","n":"Coinbase Global","s":"Finance"},
    {"t":"BLK","n":"BlackRock Inc.","s":"Finance"},
    {"t":"SCHW","n":"Charles Schwab","s":"Finance"},
    {"t":"IBKR","n":"Interactive Brokers","s":"Finance"},
    {"t":"ICE","n":"Intercontinental Exchange","s":"Finance"},
    {"t":"CME","n":"CME Group Inc.","s":"Finance"},
    {"t":"NDAQ","n":"Nasdaq Inc.","s":"Finance"},
    {"t":"HOOD","n":"Robinhood Markets","s":"Finance"},
    {"t":"SOFI","n":"SoFi Technologies","s":"Finance"},
    {"t":"AFRM","n":"Affirm Holdings","s":"Finance"},
    {"t":"UPST","n":"Upstart Holdings","s":"Finance"},
    {"t":"LC","n":"LendingClub Corporation","s":"Finance"},
    {"t":"NU","n":"Nu Holdings","s":"Finance"},
    {"t":"ALLY","n":"Ally Financial","s":"Finance"},
    {"t":"RF","n":"Regions Financial","s":"Finance"},
    {"t":"KEY","n":"KeyCorp","s":"Finance"},
    {"t":"CFG","n":"Citizens Financial Group","s":"Finance"},
    {"t":"FITB","n":"Fifth Third Bancorp","s":"Finance"},
    {"t":"HBAN","n":"Huntington Bancshares","s":"Finance"},
    {"t":"MTB","n":"M&T Bank","s":"Finance"},
    {"t":"ZION","n":"Zions Bancorporation","s":"Finance"},
    {"t":"TFC","n":"Truist Financial","s":"Finance"},
    {"t":"FRC","n":"First Republic Bank","s":"Finance"},
    {"t":"SIVB","n":"SVB Financial Group","s":"Finance"},
    {"t":"WAL","n":"Western Alliance Bancorp","s":"Finance"},
    {"t":"PACW","n":"PacWest Bancorp","s":"Finance"},
    {"t":"NYCB","n":"New York Community Bancorp","s":"Finance"},
    # ─── INSURANCE ───────────────────────────────────────────────────────────────
    {"t":"BRK-B","n":"Berkshire Hathaway Class B","s":"Finance"},
    {"t":"MET","n":"MetLife Inc.","s":"Finance"},
    {"t":"PRU","n":"Prudential Financial","s":"Finance"},
    {"t":"AFL","n":"Aflac Inc.","s":"Finance"},
    {"t":"AIG","n":"American International Group","s":"Finance"},
    {"t":"HIG","n":"Hartford Financial Services","s":"Finance"},
    {"t":"MMC","n":"Marsh & McLennan","s":"Finance"},
    {"t":"AON","n":"Aon plc","s":"Finance"},
    {"t":"CB","n":"Chubb Limited","s":"Finance"},
    {"t":"TRV","n":"Travelers Companies","s":"Finance"},
    {"t":"ALL","n":"Allstate Corporation","s":"Finance"},
    {"t":"PGR","n":"Progressive Corporation","s":"Finance"},
    # ─── HEALTHCARE / PHARMA ─────────────────────────────────────────────────────
    {"t":"JNJ","n":"Johnson & Johnson","s":"Healthcare"},
    {"t":"LLY","n":"Eli Lilly and Co.","s":"Healthcare"},
    {"t":"UNH","n":"UnitedHealth Group","s":"Healthcare"},
    {"t":"PFE","n":"Pfizer Inc.","s":"Healthcare"},
    {"t":"MRK","n":"Merck & Co.","s":"Healthcare"},
    {"t":"ABBV","n":"AbbVie Inc.","s":"Healthcare"},
    {"t":"BMY","n":"Bristol-Myers Squibb","s":"Healthcare"},
    {"t":"AMGN","n":"Amgen Inc.","s":"Healthcare"},
    {"t":"GILD","n":"Gilead Sciences","s":"Healthcare"},
    {"t":"BIIB","n":"Biogen Inc.","s":"Healthcare"},
    {"t":"MRNA","n":"Moderna Inc.","s":"Healthcare"},
    {"t":"REGN","n":"Regeneron Pharmaceuticals","s":"Healthcare"},
    {"t":"VRTX","n":"Vertex Pharmaceuticals","s":"Healthcare"},
    {"t":"ISRG","n":"Intuitive Surgical","s":"Healthcare"},
    {"t":"SYK","n":"Stryker Corporation","s":"Healthcare"},
    {"t":"MDT","n":"Medtronic plc","s":"Healthcare"},
    {"t":"BSX","n":"Boston Scientific","s":"Healthcare"},
    {"t":"BDX","n":"Becton Dickinson","s":"Healthcare"},
    {"t":"ZBH","n":"Zimmer Biomet","s":"Healthcare"},
    {"t":"EW","n":"Edwards Lifesciences","s":"Healthcare"},
    {"t":"CVS","n":"CVS Health","s":"Healthcare"},
    {"t":"CI","n":"Cigna Group","s":"Healthcare"},
    {"t":"HUM","n":"Humana Inc.","s":"Healthcare"},
    {"t":"MCK","n":"McKesson Corporation","s":"Healthcare"},
    {"t":"ABC","n":"AmerisourceBergen","s":"Healthcare"},
    {"t":"CAH","n":"Cardinal Health","s":"Healthcare"},
    {"t":"THC","n":"Tenet Healthcare","s":"Healthcare"},
    {"t":"HCA","n":"HCA Healthcare","s":"Healthcare"},
    {"t":"UHS","n":"Universal Health Services","s":"Healthcare"},
    {"t":"CNC","n":"Centene Corporation","s":"Healthcare"},
    {"t":"MOH","n":"Molina Healthcare","s":"Healthcare"},
    {"t":"ANTM","n":"Elevance Health (Anthem)","s":"Healthcare"},
    {"t":"ZTS","n":"Zoetis Inc.","s":"Healthcare"},
    {"t":"IDXX","n":"IDEXX Laboratories","s":"Healthcare"},
    {"t":"BAX","n":"Baxter International","s":"Healthcare"},
    {"t":"ABT","n":"Abbott Laboratories","s":"Healthcare"},
    {"t":"DHR","n":"Danaher Corporation","s":"Healthcare"},
    {"t":"TMO","n":"Thermo Fisher Scientific","s":"Healthcare"},
    {"t":"A","n":"Agilent Technologies","s":"Healthcare"},
    {"t":"IQV","n":"IQVIA Holdings","s":"Healthcare"},
    {"t":"CRL","n":"Charles River Laboratories","s":"Healthcare"},
    {"t":"MTD","n":"Mettler-Toledo International","s":"Healthcare"},
    {"t":"WAT","n":"Waters Corporation","s":"Healthcare"},
    # ─── CONSUMER STAPLES ────────────────────────────────────────────────────────
    {"t":"WMT","n":"Walmart Inc.","s":"Consumer Staples"},
    {"t":"COST","n":"Costco Wholesale","s":"Consumer Staples"},
    {"t":"KO","n":"Coca-Cola Co.","s":"Consumer Staples"},
    {"t":"PEP","n":"PepsiCo Inc.","s":"Consumer Staples"},
    {"t":"PG","n":"Procter & Gamble","s":"Consumer Staples"},
    {"t":"CL","n":"Colgate-Palmolive","s":"Consumer Staples"},
    {"t":"KMB","n":"Kimberly-Clark","s":"Consumer Staples"},
    {"t":"GIS","n":"General Mills","s":"Consumer Staples"},
    {"t":"K","n":"Kellanova","s":"Consumer Staples"},
    {"t":"HSY","n":"Hershey Company","s":"Consumer Staples"},
    {"t":"MO","n":"Altria Group","s":"Consumer Staples"},
    {"t":"PM","n":"Philip Morris International","s":"Consumer Staples"},
    {"t":"MDLZ","n":"Mondelez International","s":"Consumer Staples"},
    {"t":"STZ","n":"Constellation Brands","s":"Consumer Staples"},
    {"t":"BUD","n":"Anheuser-Busch InBev","s":"Consumer Staples"},
    {"t":"TAP","n":"Molson Coors Beverage","s":"Consumer Staples"},
    {"t":"CHD","n":"Church & Dwight","s":"Consumer Staples"},
    {"t":"CLX","n":"Clorox Company","s":"Consumer Staples"},
    {"t":"EL","n":"Estee Lauder Companies","s":"Consumer Staples"},
    {"t":"KR","n":"Kroger Co.","s":"Consumer Staples"},
    {"t":"SFM","n":"Sprouts Farmers Market","s":"Consumer Staples"},
    {"t":"GO","n":"Grocery Outlet Holding","s":"Consumer Staples"},
    # ─── CONSUMER DISCRETIONARY ──────────────────────────────────────────────────
    {"t":"TGT","n":"Target Corporation","s":"Consumer Discretionary"},
    {"t":"HD","n":"Home Depot","s":"Consumer Discretionary"},
    {"t":"LOW","n":"Lowe's Companies","s":"Consumer Discretionary"},
    {"t":"MCD","n":"McDonald's Corp.","s":"Consumer Discretionary"},
    {"t":"SBUX","n":"Starbucks Corporation","s":"Consumer Discretionary"},
    {"t":"NKE","n":"Nike Inc.","s":"Consumer Discretionary"},
    {"t":"TJX","n":"TJX Companies","s":"Consumer Discretionary"},
    {"t":"ROST","n":"Ross Stores","s":"Consumer Discretionary"},
    {"t":"YUM","n":"Yum! Brands","s":"Consumer Discretionary"},
    {"t":"CMG","n":"Chipotle Mexican Grill","s":"Consumer Discretionary"},
    {"t":"DPZ","n":"Domino's Pizza","s":"Consumer Discretionary"},
    {"t":"QSR","n":"Restaurant Brands Int'l","s":"Consumer Discretionary"},
    {"t":"DKNG","n":"DraftKings Inc.","s":"Consumer Discretionary"},
    {"t":"ETSY","n":"Etsy Inc.","s":"Consumer Discretionary"},
    {"t":"EBAY","n":"eBay Inc.","s":"Consumer Discretionary"},
    {"t":"BKNG","n":"Booking Holdings","s":"Consumer Discretionary"},
    {"t":"EXPE","n":"Expedia Group","s":"Consumer Discretionary"},
    {"t":"ABNB","n":"Airbnb Inc.","s":"Consumer Discretionary"},
    {"t":"UBER","n":"Uber Technologies","s":"Consumer Discretionary"},
    {"t":"LYFT","n":"Lyft Inc.","s":"Consumer Discretionary"},
    {"t":"DASH","n":"DoorDash Inc.","s":"Consumer Discretionary"},
    {"t":"TRIP","n":"TripAdvisor Inc.","s":"Consumer Discretionary"},
    {"t":"CCL","n":"Carnival Corporation","s":"Consumer Discretionary"},
    {"t":"RCL","n":"Royal Caribbean Group","s":"Consumer Discretionary"},
    {"t":"NCLH","n":"Norwegian Cruise Line","s":"Consumer Discretionary"},
    {"t":"MGM","n":"MGM Resorts International","s":"Consumer Discretionary"},
    {"t":"WYNN","n":"Wynn Resorts","s":"Consumer Discretionary"},
    {"t":"LVS","n":"Las Vegas Sands","s":"Consumer Discretionary"},
    {"t":"CZR","n":"Caesars Entertainment","s":"Consumer Discretionary"},
    {"t":"PENN","n":"Penn Entertainment","s":"Consumer Discretionary"},
    {"t":"VFC","n":"VF Corporation","s":"Consumer Discretionary"},
    {"t":"RL","n":"Ralph Lauren","s":"Consumer Discretionary"},
    {"t":"PVH","n":"PVH Corp.","s":"Consumer Discretionary"},
    {"t":"HBI","n":"Hanesbrands Inc.","s":"Consumer Discretionary"},
    {"t":"ANF","n":"Abercrombie & Fitch","s":"Consumer Discretionary"},
    {"t":"AEO","n":"American Eagle Outfitters","s":"Consumer Discretionary"},
    {"t":"URBN","n":"Urban Outfitters","s":"Consumer Discretionary"},
    {"t":"GPS","n":"Gap Inc.","s":"Consumer Discretionary"},
    {"t":"M","n":"Macy's Inc.","s":"Consumer Discretionary"},
    {"t":"KSS","n":"Kohl's Corporation","s":"Consumer Discretionary"},
    {"t":"JWN","n":"Nordstrom Inc.","s":"Consumer Discretionary"},
    {"t":"BBY","n":"Best Buy Co.","s":"Consumer Discretionary"},
    {"t":"GME","n":"GameStop Corp.","s":"Consumer Discretionary"},
    {"t":"AMC","n":"AMC Entertainment","s":"Consumer Discretionary"},
    # ─── ENERGY ──────────────────────────────────────────────────────────────────
    {"t":"XOM","n":"ExxonMobil","s":"Energy"},
    {"t":"CVX","n":"Chevron Corporation","s":"Energy"},
    {"t":"COP","n":"ConocoPhillips","s":"Energy"},
    {"t":"EOG","n":"EOG Resources","s":"Energy"},
    {"t":"SLB","n":"SLB (Schlumberger)","s":"Energy"},
    {"t":"OXY","n":"Occidental Petroleum","s":"Energy"},
    {"t":"MPC","n":"Marathon Petroleum","s":"Energy"},
    {"t":"VLO","n":"Valero Energy","s":"Energy"},
    {"t":"PSX","n":"Phillips 66","s":"Energy"},
    {"t":"HAL","n":"Halliburton Company","s":"Energy"},
    {"t":"BKR","n":"Baker Hughes","s":"Energy"},
    {"t":"DVN","n":"Devon Energy","s":"Energy"},
    {"t":"FANG","n":"Diamondback Energy","s":"Energy"},
    {"t":"APA","n":"APA Corporation","s":"Energy"},
    {"t":"CTRA","n":"Coterra Energy","s":"Energy"},
    {"t":"MRO","n":"Marathon Oil Corporation","s":"Energy"},
    {"t":"ENPH","n":"Enphase Energy","s":"Energy"},
    {"t":"SEDG","n":"SolarEdge Technologies","s":"Energy"},
    {"t":"FSLR","n":"First Solar Inc.","s":"Energy"},
    {"t":"PLUG","n":"Plug Power Inc.","s":"Energy"},
    {"t":"BE","n":"Bloom Energy","s":"Energy"},
    {"t":"RUN","n":"Sunrun Inc.","s":"Energy"},
    {"t":"NOVA","n":"Sunnova Energy","s":"Energy"},
    {"t":"OKE","n":"ONEOK Inc.","s":"Energy"},
    {"t":"KMI","n":"Kinder Morgan","s":"Energy"},
    {"t":"WMB","n":"Williams Companies","s":"Energy"},
    {"t":"LNG","n":"Cheniere Energy","s":"Energy"},
    {"t":"ET","n":"Energy Transfer Partners","s":"Energy"},
    {"t":"EPD","n":"Enterprise Products Partners","s":"Energy"},
    # ─── INDUSTRIALS / AEROSPACE ─────────────────────────────────────────────────
    {"t":"BA","n":"Boeing Company","s":"Industrials"},
    {"t":"LMT","n":"Lockheed Martin","s":"Industrials"},
    {"t":"RTX","n":"RTX Corporation","s":"Industrials"},
    {"t":"GE","n":"GE Aerospace","s":"Industrials"},
    {"t":"NOC","n":"Northrop Grumman","s":"Industrials"},
    {"t":"GD","n":"General Dynamics","s":"Industrials"},
    {"t":"HII","n":"Huntington Ingalls","s":"Industrials"},
    {"t":"CAT","n":"Caterpillar Inc.","s":"Industrials"},
    {"t":"DE","n":"Deere & Company","s":"Industrials"},
    {"t":"HON","n":"Honeywell International","s":"Industrials"},
    {"t":"MMM","n":"3M Company","s":"Industrials"},
    {"t":"EMR","n":"Emerson Electric","s":"Industrials"},
    {"t":"ETN","n":"Eaton Corporation","s":"Industrials"},
    {"t":"ROK","n":"Rockwell Automation","s":"Industrials"},
    {"t":"PH","n":"Parker Hannifin","s":"Industrials"},
    {"t":"IR","n":"Ingersoll Rand","s":"Industrials"},
    {"t":"XYL","n":"Xylem Inc.","s":"Industrials"},
    {"t":"UPS","n":"United Parcel Service","s":"Industrials"},
    {"t":"FDX","n":"FedEx Corporation","s":"Industrials"},
    {"t":"JBHT","n":"J.B. Hunt Transport","s":"Industrials"},
    {"t":"CSX","n":"CSX Corporation","s":"Industrials"},
    {"t":"UNP","n":"Union Pacific","s":"Industrials"},
    {"t":"NSC","n":"Norfolk Southern","s":"Industrials"},
    {"t":"DAL","n":"Delta Air Lines","s":"Industrials"},
    {"t":"UAL","n":"United Airlines Holdings","s":"Industrials"},
    {"t":"AAL","n":"American Airlines","s":"Industrials"},
    {"t":"LUV","n":"Southwest Airlines","s":"Industrials"},
    {"t":"ALGT","n":"Allegiant Travel","s":"Industrials"},
    {"t":"SAVE","n":"Spirit Airlines","s":"Industrials"},
    {"t":"SPCE","n":"Virgin Galactic","s":"Industrials"},
    {"t":"RKLB","n":"Rocket Lab USA","s":"Industrials"},
    {"t":"ASTS","n":"AST SpaceMobile","s":"Industrials"},
    {"t":"ASTR","n":"Astra Space","s":"Industrials"},
    {"t":"ACHR","n":"Archer Aviation","s":"Industrials"},
    {"t":"JOBY","n":"Joby Aviation","s":"Industrials"},
    # ─── COMMUNICATIONS / MEDIA ──────────────────────────────────────────────────
    {"t":"NFLX","n":"Netflix Inc.","s":"Communication Services"},
    {"t":"DIS","n":"Walt Disney Company","s":"Communication Services"},
    {"t":"CMCSA","n":"Comcast Corporation","s":"Communication Services"},
    {"t":"T","n":"AT&T Inc.","s":"Communication Services"},
    {"t":"VZ","n":"Verizon Communications","s":"Communication Services"},
    {"t":"TMUS","n":"T-Mobile US","s":"Communication Services"},
    {"t":"PARA","n":"Paramount Global","s":"Communication Services"},
    {"t":"WBD","n":"Warner Bros. Discovery","s":"Communication Services"},
    {"t":"SNAP","n":"Snap Inc.","s":"Communication Services"},
    {"t":"PINS","n":"Pinterest Inc.","s":"Communication Services"},
    {"t":"SPOT","n":"Spotify Technology","s":"Communication Services"},
    {"t":"MTCH","n":"Match Group","s":"Communication Services"},
    {"t":"EA","n":"Electronic Arts","s":"Communication Services"},
    {"t":"TTWO","n":"Take-Two Interactive","s":"Communication Services"},
    {"t":"RBLX","n":"Roblox Corporation","s":"Communication Services"},
    {"t":"U","n":"Unity Software","s":"Communication Services"},
    {"t":"NTES","n":"NetEase Inc.","s":"Communication Services"},
    {"t":"BIDU","n":"Baidu Inc.","s":"Communication Services"},
    {"t":"TENCENT","n":"Tencent Holdings (OTC)","s":"Communication Services"},
    {"t":"IACI","n":"IAC Inc.","s":"Communication Services"},
    {"t":"LBRDA","n":"Liberty Broadband","s":"Communication Services"},
    {"t":"CHTR","n":"Charter Communications","s":"Communication Services"},
    {"t":"LUMN","n":"Lumen Technologies","s":"Communication Services"},
    {"t":"SIRI","n":"Sirius XM Holdings","s":"Communication Services"},
    # ─── AUTOMOTIVE / EV ─────────────────────────────────────────────────────────
    {"t":"F","n":"Ford Motor Company","s":"Consumer Discretionary"},
    {"t":"GM","n":"General Motors","s":"Consumer Discretionary"},
    {"t":"RIVN","n":"Rivian Automotive","s":"Consumer Discretionary"},
    {"t":"LCID","n":"Lucid Group","s":"Consumer Discretionary"},
    {"t":"NIO","n":"NIO Inc.","s":"Consumer Discretionary"},
    {"t":"LI","n":"Li Auto Inc.","s":"Consumer Discretionary"},
    {"t":"XPEV","n":"XPeng Inc.","s":"Consumer Discretionary"},
    {"t":"TM","n":"Toyota Motor","s":"Consumer Discretionary"},
    {"t":"HMC","n":"Honda Motor Co.","s":"Consumer Discretionary"},
    {"t":"STLA","n":"Stellantis NV","s":"Consumer Discretionary"},
    {"t":"BWA","n":"BorgWarner Inc.","s":"Consumer Discretionary"},
    {"t":"LEA","n":"Lear Corporation","s":"Consumer Discretionary"},
    {"t":"MGA","n":"Magna International","s":"Consumer Discretionary"},
    # ─── REAL ESTATE (REITs) ─────────────────────────────────────────────────────
    {"t":"AMT","n":"American Tower","s":"Real Estate"},
    {"t":"PLD","n":"Prologis","s":"Real Estate"},
    {"t":"CCI","n":"Crown Castle","s":"Real Estate"},
    {"t":"EQIX","n":"Equinix Inc.","s":"Real Estate"},
    {"t":"SPG","n":"Simon Property Group","s":"Real Estate"},
    {"t":"O","n":"Realty Income Corp.","s":"Real Estate"},
    {"t":"VICI","n":"VICI Properties","s":"Real Estate"},
    {"t":"WELL","n":"Welltower Inc.","s":"Real Estate"},
    {"t":"DLR","n":"Digital Realty Trust","s":"Real Estate"},
    {"t":"IRM","n":"Iron Mountain","s":"Real Estate"},
    {"t":"PSA","n":"Public Storage","s":"Real Estate"},
    {"t":"EXR","n":"Extra Space Storage","s":"Real Estate"},
    {"t":"AVB","n":"AvalonBay Communities","s":"Real Estate"},
    {"t":"EQR","n":"Equity Residential","s":"Real Estate"},
    {"t":"NLY","n":"Annaly Capital Management","s":"Real Estate"},
    {"t":"AGNC","n":"AGNC Investment Corp.","s":"Real Estate"},
    {"t":"ARE","n":"Alexandria Real Estate","s":"Real Estate"},
    {"t":"BXP","n":"Boston Properties","s":"Real Estate"},
    {"t":"VNO","n":"Vornado Realty Trust","s":"Real Estate"},
    {"t":"SLG","n":"SL Green Realty","s":"Real Estate"},
    {"t":"KIM","n":"Kimco Realty","s":"Real Estate"},
    {"t":"REG","n":"Regency Centers","s":"Real Estate"},
    {"t":"SITC","n":"Site Centers Corp.","s":"Real Estate"},
    {"t":"MAA","n":"Mid-America Apartment","s":"Real Estate"},
    {"t":"UDR","n":"UDR Inc.","s":"Real Estate"},
    {"t":"CPT","n":"Camden Property Trust","s":"Real Estate"},
    # ─── UTILITIES ───────────────────────────────────────────────────────────────
    {"t":"NEE","n":"NextEra Energy","s":"Utilities"},
    {"t":"DUK","n":"Duke Energy","s":"Utilities"},
    {"t":"SO","n":"Southern Company","s":"Utilities"},
    {"t":"AEP","n":"American Electric Power","s":"Utilities"},
    {"t":"EXC","n":"Exelon Corporation","s":"Utilities"},
    {"t":"XEL","n":"Xcel Energy","s":"Utilities"},
    {"t":"PCG","n":"PG&E Corporation","s":"Utilities"},
    {"t":"SRE","n":"Sempra Energy","s":"Utilities"},
    {"t":"ED","n":"Consolidated Edison","s":"Utilities"},
    {"t":"AWK","n":"American Water Works","s":"Utilities"},
    {"t":"WEC","n":"WEC Energy Group","s":"Utilities"},
    {"t":"ES","n":"Eversource Energy","s":"Utilities"},
    {"t":"DTE","n":"DTE Energy","s":"Utilities"},
    {"t":"CMS","n":"CMS Energy","s":"Utilities"},
    {"t":"PPL","n":"PPL Corporation","s":"Utilities"},
    {"t":"NI","n":"NiSource Inc.","s":"Utilities"},
    {"t":"LNT","n":"Alliant Energy","s":"Utilities"},
    {"t":"EVRG","n":"Evergy Inc.","s":"Utilities"},
    {"t":"AES","n":"AES Corporation","s":"Utilities"},
    {"t":"NRG","n":"NRG Energy","s":"Utilities"},
    # ─── MATERIALS ───────────────────────────────────────────────────────────────
    {"t":"LIN","n":"Linde plc","s":"Materials"},
    {"t":"APD","n":"Air Products & Chemicals","s":"Materials"},
    {"t":"SHW","n":"Sherwin-Williams","s":"Materials"},
    {"t":"ECL","n":"Ecolab Inc.","s":"Materials"},
    {"t":"NEM","n":"Newmont Corporation","s":"Materials"},
    {"t":"FCX","n":"Freeport-McMoRan","s":"Materials"},
    {"t":"NUE","n":"Nucor Corporation","s":"Materials"},
    {"t":"AA","n":"Alcoa Corporation","s":"Materials"},
    {"t":"X","n":"U.S. Steel","s":"Materials"},
    {"t":"CLF","n":"Cleveland-Cliffs","s":"Materials"},
    {"t":"CF","n":"CF Industries","s":"Materials"},
    {"t":"MOS","n":"Mosaic Company","s":"Materials"},
    {"t":"DD","n":"DuPont de Nemours","s":"Materials"},
    {"t":"DOW","n":"Dow Inc.","s":"Materials"},
    {"t":"LYB","n":"LyondellBasell Industries","s":"Materials"},
    {"t":"WRK","n":"WestRock Company","s":"Materials"},
    {"t":"IP","n":"International Paper","s":"Materials"},
    {"t":"PKG","n":"Packaging Corp. of America","s":"Materials"},
    {"t":"SEE","n":"Sealed Air Corporation","s":"Materials"},
    {"t":"ATI","n":"Allegheny Technologies","s":"Materials"},
    {"t":"RS","n":"Reliance Steel & Aluminum","s":"Materials"},
    {"t":"CMC","n":"Commercial Metals Company","s":"Materials"},
    {"t":"WOR","n":"Worthington Industries","s":"Materials"},
    {"t":"CRH","n":"CRH plc","s":"Materials"},
    {"t":"MLM","n":"Martin Marietta Materials","s":"Materials"},
    {"t":"VMC","n":"Vulcan Materials Company","s":"Materials"},
    {"t":"EXP","n":"Eagle Materials Inc.","s":"Materials"},
    {"t":"GCC","n":"Western Cement Corp","s":"Materials"},
    # ─── E-COMMERCE / INTERNET ───────────────────────────────────────────────────
    {"t":"BABA","n":"Alibaba Group","s":"Consumer Discretionary"},
    {"t":"JD","n":"JD.com Inc.","s":"Consumer Discretionary"},
    {"t":"PDD","n":"PDD Holdings (Temu)","s":"Consumer Discretionary"},
    {"t":"SE","n":"Sea Limited","s":"Consumer Discretionary"},
    {"t":"MELI","n":"MercadoLibre Inc.","s":"Consumer Discretionary"},
    {"t":"GRAB","n":"Grab Holdings","s":"Consumer Discretionary"},
    {"t":"CPNG","n":"Coupang Inc.","s":"Consumer Discretionary"},
    {"t":"WIX","n":"Wix.com Ltd.","s":"Technology"},
    {"t":"BIGC","n":"BigCommerce Holdings","s":"Technology"},
    # ─── CRYPTO-RELATED ──────────────────────────────────────────────────────────
    {"t":"MSTR","n":"MicroStrategy Inc.","s":"Crypto-Related"},
    {"t":"MARA","n":"Marathon Digital Holdings","s":"Crypto-Related"},
    {"t":"RIOT","n":"Riot Platforms","s":"Crypto-Related"},
    {"t":"HUT","n":"Hut 8 Mining Corp.","s":"Crypto-Related"},
    {"t":"BTBT","n":"Bit Digital Inc.","s":"Crypto-Related"},
    {"t":"CLSK","n":"CleanSpark Inc.","s":"Crypto-Related"},
    {"t":"CIFR","n":"Cipher Mining Inc.","s":"Crypto-Related"},
    {"t":"WULF","n":"TeraWulf Inc.","s":"Crypto-Related"},
    {"t":"IREN","n":"Iris Energy","s":"Crypto-Related"},
    # ─── ETFs ────────────────────────────────────────────────────────────────────
    {"t":"SPY","n":"SPDR S&P 500 ETF","s":"ETF"},
    {"t":"QQQ","n":"Invesco Nasdaq-100 ETF","s":"ETF"},
    {"t":"DIA","n":"SPDR Dow Jones ETF","s":"ETF"},
    {"t":"IWM","n":"iShares Russell 2000 ETF","s":"ETF"},
    {"t":"VTI","n":"Vanguard Total Market ETF","s":"ETF"},
    {"t":"VOO","n":"Vanguard S&P 500 ETF","s":"ETF"},
    {"t":"GLD","n":"SPDR Gold Shares ETF","s":"ETF"},
    {"t":"SLV","n":"iShares Silver Trust ETF","s":"ETF"},
    {"t":"USO","n":"United States Oil Fund ETF","s":"ETF"},
    {"t":"XLF","n":"Financial Select Sector SPDR","s":"ETF"},
    {"t":"XLK","n":"Technology Select SPDR","s":"ETF"},
    {"t":"XLE","n":"Energy Select Sector SPDR","s":"ETF"},
    {"t":"XLV","n":"Health Care Select SPDR","s":"ETF"},
    {"t":"XLI","n":"Industrial Select SPDR","s":"ETF"},
    {"t":"XLU","n":"Utilities Select SPDR","s":"ETF"},
    {"t":"XLP","n":"Consumer Staples SPDR","s":"ETF"},
    {"t":"XLY","n":"Consumer Discretionary SPDR","s":"ETF"},
    {"t":"XLRE","n":"Real Estate Select SPDR","s":"ETF"},
    {"t":"XLB","n":"Materials Select SPDR","s":"ETF"},
    {"t":"XLC","n":"Communication Services SPDR","s":"ETF"},
    {"t":"ARKK","n":"ARK Innovation ETF","s":"ETF"},
    {"t":"ARKG","n":"ARK Genomic Revolution ETF","s":"ETF"},
    {"t":"ARKW","n":"ARK Next Generation Internet ETF","s":"ETF"},
    {"t":"ARKF","n":"ARK Fintech Innovation ETF","s":"ETF"},
    {"t":"VNQ","n":"Vanguard Real Estate ETF","s":"ETF"},
    {"t":"AGG","n":"iShares Core US Aggregate Bond ETF","s":"ETF"},
    {"t":"TLT","n":"iShares 20+ Year Treasury Bond ETF","s":"ETF"},
    {"t":"HYG","n":"iShares iBoxx High Yield Corp Bond ETF","s":"ETF"},
    {"t":"LQD","n":"iShares iBoxx Invest Grade Corp Bond ETF","s":"ETF"},
    {"t":"EEM","n":"iShares MSCI Emerging Markets ETF","s":"ETF"},
    {"t":"EFA","n":"iShares MSCI EAFE ETF","s":"ETF"},
    {"t":"VWO","n":"Vanguard FTSE Emerging Markets ETF","s":"ETF"},
    {"t":"IAU","n":"iShares Gold Trust ETF","s":"ETF"},
    {"t":"GBTC","n":"Grayscale Bitcoin Trust","s":"ETF"},
    {"t":"BITO","n":"ProShares Bitcoin Strategy ETF","s":"ETF"},
    {"t":"TQQQ","n":"ProShares UltraPro QQQ (3x)","s":"ETF"},
    {"t":"SQQQ","n":"ProShares UltraPro Short QQQ (3x)","s":"ETF"},
    {"t":"SPXL","n":"Direxion Daily S&P500 Bull 3X ETF","s":"ETF"},
    {"t":"SPXS","n":"Direxion Daily S&P500 Bear 3X ETF","s":"ETF"},
    {"t":"UPRO","n":"ProShares UltraPro S&P500 (3x)","s":"ETF"},
    {"t":"LABU","n":"Direxion Daily S&P Biotech Bull 3X","s":"ETF"},
    {"t":"LABD","n":"Direxion Daily S&P Biotech Bear 3X","s":"ETF"},
    {"t":"FNGU","n":"MicroSectors FANG+ Index 3X","s":"ETF"},
    {"t":"SMH","n":"VanEck Semiconductor ETF","s":"ETF"},
    {"t":"IBB","n":"iShares Biotechnology ETF","s":"ETF"},
    {"t":"XBI","n":"SPDR S&P Biotech ETF","s":"ETF"},
    {"t":"KWEB","n":"KraneShares CSI China Internet ETF","s":"ETF"},
    {"t":"FXI","n":"iShares China Large-Cap ETF","s":"ETF"},
    {"t":"NDIA","n":"Global X India Active ETF","s":"ETF"},
    {"t":"INDA","n":"iShares MSCI India ETF","s":"ETF"},
    {"t":"RSX","n":"VanEck Russia ETF (suspended)","s":"ETF"},
    {"t":"EWZ","n":"iShares MSCI Brazil ETF","s":"ETF"},
    {"t":"EWJ","n":"iShares MSCI Japan ETF","s":"ETF"},
    {"t":"IYR","n":"iShares US Real Estate ETF","s":"ETF"},
    {"t":"PDBC","n":"Invesco Optimum Yield Diversified Commodity ETF","s":"ETF"},
    {"t":"DBO","n":"Invesco DB Oil Fund ETF","s":"ETF"},
    {"t":"DBB","n":"Invesco DB Base Metals Fund ETF","s":"ETF"},
    {"t":"UNG","n":"United States Natural Gas Fund ETF","s":"ETF"},
    {"t":"GDXJ","n":"VanEck Junior Gold Miners ETF","s":"ETF"},
    {"t":"GDX","n":"VanEck Gold Miners ETF","s":"ETF"},
    {"t":"SLX","n":"VanEck Steel ETF","s":"ETF"},
    {"t":"JETS","n":"US Global Jets ETF","s":"ETF"},
    {"t":"AWAY","n":"ETFMG Travel Tech ETF","s":"ETF"},
    {"t":"PEJ","n":"Invesco Dynamic Leisure & Entertainment ETF","s":"ETF"},
    {"t":"ROBO","n":"ROBO Global Robotics and Automation ETF","s":"ETF"},
    {"t":"BOTZ","n":"Global X Robotics & Artificial Intelligence ETF","s":"ETF"},
    {"t":"HACK","n":"ETFMG Prime Cyber Security ETF","s":"ETF"},
    {"t":"BUG","n":"Global X Cybersecurity ETF","s":"ETF"},
    {"t":"WCLD","n":"WisdomTree Cloud Computing ETF","s":"ETF"},
    {"t":"SKYY","n":"First Trust Cloud Computing ETF","s":"ETF"},
    {"t":"CLOU","n":"Global X Cloud Computing ETF","s":"ETF"},
    {"t":"METV","n":"Roundhill Ball Metaverse ETF","s":"ETF"},
    {"t":"AIQ","n":"Global X Artificial Intelligence & Tech ETF","s":"ETF"},
    {"t":"DRIV","n":"Global X Autonomous & Electric Vehicles ETF","s":"ETF"},
    {"t":"IDRV","n":"iShares Self-Driving EV and Tech ETF","s":"ETF"},
    {"t":"LIT","n":"Global X Lithium & Battery Tech ETF","s":"ETF"},
    {"t":"ICLN","n":"iShares Global Clean Energy ETF","s":"ETF"},
    {"t":"TAN","n":"Invesco Solar ETF","s":"ETF"},
    {"t":"FAN","n":"First Trust Global Wind Energy ETF","s":"ETF"},
    {"t":"HERO","n":"Global X Video Games & Esports ETF","s":"ETF"},
    {"t":"ESPO","n":"VanEck Video Gaming and eSports ETF","s":"ETF"},
    {"t":"MSOS","n":"AdvisorShares Pure US Cannabis ETF","s":"ETF"},
    {"t":"MJ","n":"ETFMG Alternative Harvest ETF (Cannabis)","s":"ETF"},
    {"t":"GRID","n":"First Trust NASDAQ Clean Edge Smart Grid ETF","s":"ETF"},
    # ─── BIOTECH SPECULATIVE ─────────────────────────────────────────────────────
    {"t":"NVAX","n":"Novavax Inc.","s":"Healthcare"},
    {"t":"BNTX","n":"BioNTech SE","s":"Healthcare"},
    {"t":"OCGN","n":"Ocugen Inc.","s":"Healthcare"},
    {"t":"SGEN","n":"Seagen Inc.","s":"Healthcare"},
    {"t":"BGNE","n":"BeiGene Ltd.","s":"Healthcare"},
    {"t":"ZLAB","n":"Zymeworks Inc.","s":"Healthcare"},
    {"t":"ACAD","n":"ACADIA Pharmaceuticals","s":"Healthcare"},
    {"t":"SAGE","n":"Sage Therapeutics","s":"Healthcare"},
    {"t":"FATE","n":"Fate Therapeutics","s":"Healthcare"},
    {"t":"BEAM","n":"Beam Therapeutics","s":"Healthcare"},
    {"t":"NTLA","n":"Intellia Therapeutics","s":"Healthcare"},
    {"t":"EDIT","n":"Editas Medicine","s":"Healthcare"},
    {"t":"CRSP","n":"CRISPR Therapeutics","s":"Healthcare"},
    {"t":"PGEN","n":"Precigen Inc.","s":"Healthcare"},
    {"t":"NVTA","n":"Invitae Corporation","s":"Healthcare"},
    {"t":"EXAS","n":"Exact Sciences","s":"Healthcare"},
    {"t":"GKOS","n":"Glaukos Corporation","s":"Healthcare"},
    {"t":"ACVA","n":"ACV Auctions","s":"Healthcare"},
    {"t":"RXRX","n":"Recursion Pharmaceuticals","s":"Healthcare"},
    {"t":"SDGR","n":"Schrodinger Inc.","s":"Healthcare"},
    # ─── MEME / HIGH VOLATILITY ──────────────────────────────────────────────────
    {"t":"BBBY","n":"Bed Bath & Beyond","s":"Meme Stocks"},
    {"t":"GME","n":"GameStop Corp.","s":"Meme Stocks"},
    {"t":"AMC","n":"AMC Entertainment","s":"Meme Stocks"},
    {"t":"CLOV","n":"Clover Health Investments","s":"Meme Stocks"},
    {"t":"WISH","n":"ContextLogic Inc.","s":"Meme Stocks"},
    {"t":"KOSS","n":"Koss Corporation","s":"Meme Stocks"},
    {"t":"EXPR","n":"Express Inc.","s":"Meme Stocks"},
    {"t":"BB","n":"BlackBerry Limited","s":"Meme Stocks"},
    {"t":"NAKD","n":"Naked Brand Group","s":"Meme Stocks"},
    # ─── INDIAN EQUITIES (TATA GROUP & MAJORS) ───────────────────────────────────
    {"t":"TATAMOTORS.NS","n":"Tata Motors Limited","s":"Automotive"},
    {"t":"TCS.NS","n":"Tata Consultancy Services","s":"Technology"},
    {"t":"TATASTEEL.NS","n":"Tata Steel Limited","s":"Materials"},
    {"t":"TATAPOWER.NS","n":"Tata Power Company","s":"Utilities"},
    {"t":"TITAN.NS","n":"Titan Company Limited","s":"Consumer Discretionary"},
    {"t":"TATACONSUM.NS","n":"Tata Consumer Products","s":"Consumer Staples"},
    {"t":"TATACHEM.NS","n":"Tata Chemicals","s":"Materials"},
    {"t":"TRENT.NS","n":"Trent Limited","s":"Consumer Discretionary"},
    {"t":"VOLTAS.NS","n":"Voltas Limited","s":"Industrials"},
    {"t":"INDHOTEL.NS","n":"Indian Hotels Company","s":"Consumer Discretionary"},
    {"t":"TATACOMM.NS","n":"Tata Communications","s":"Communication Services"},
    {"t":"TATAELXSI.NS","n":"Tata Elxsi","s":"Technology"},
    {"t":"RELIANCE.NS","n":"Reliance Industries","s":"Energy"},
    {"t":"HDFCBANK.NS","n":"HDFC Bank Limited","s":"Finance"},
    {"t":"INFY.NS","n":"Infosys Limited","s":"Technology"},
    {"t":"ICICIBANK.NS","n":"ICICI Bank Limited","s":"Finance"},
    {"t":"SBIN.NS","n":"State Bank of India","s":"Finance"},
]

def build():
    data = [{"ticker": x["t"], "name": x["n"], "sector": x["s"]} for x in TICKERS]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"✅ Saved {len(data)} tickers → {OUT}")
    from collections import Counter
    c = Counter(x["s"] for x in TICKERS)
    print("\nBy sector:")
    for sec, cnt in sorted(c.items(), key=lambda x: -x[1]):
        print(f"  {cnt:4d}  {sec}")

if __name__ == "__main__":
    build()
